
all:

clean:
	make -C ./tests clean
	make -C ./demo clean

fclean:
	make -C ./tests fclean
	make -C ./demo fclean

tests:
	make -C ./tests run

demo:
	make -C ./demo run

.PHONY: all clean fclean tests demo
